### ISSUE TITLE
Транспиляция JS: Babel

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/platform#1]
Предлагается использовать для поддержки большего количества браузеров и для сборки JS-модулей Babel. 

Его поддержка есть в eleventy ([вот тут ссылка](https://www.11ty.dev/docs/plugins/)), устанавливается в виде зависимости [eleventy-plugin-babel](https://www.npmjs.com/package/eleventy-plugin-babel). 

Можно не тянуть целый webpack, если он нам не нужен, и использовать только на deploy- или build-сборках.

**Comment by akellbl4** [comment]
Бабел не умеет склеивать файлы по импортам, если это окей, то вроде не сложно. Могу сделать
