### ISSUE TITLE
Отключить preview для draft-сборок

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/platform#159]
<img width="926" alt="Снимок экрана 2021-05-27 в 16 17 16" src="https://user-images.githubusercontent.com/50330458/119966511-0bec8300-bfb4-11eb-9ca6-addc24a51094.png">

Во время создания [пиара в черновиках](https://github.com/Y-Doka/content/pull/722), ломается превью. Думаю, что стоит отключить.

Возможно, стоит включить превью по кнопке.

**Comment by igsekor** [comment]
@furtivite добавил [решение](https://github.com/Y-Doka/content/pull/725). Должно заработать :)
