### ISSUE TITLE
Прикрутить новый домен doka.guide к Netlify и сборке 

### ISSUE THREAD

**Issue by pepelsbey** [Y-Doka/platform#177]
Мы сейчас храним старый сайт на [y-doka.site](https://y-doka.site/), а новый черновик на [new.y-doka.site](https://new.y-doka.site/). Предлагаю заменить место для черновика со старого поддомена на новый домен [doka.guide](https://doka.guide/).

- Там заранее появится контент для поисковиков
- Мы заранее прикрутим домен и настроим сборку

Я готов поменять в панели управления NS-сервера на нужные, главное сказать какие :)

Как подключим домен — начнём переезд организации и замену путей.

**Comment by furtivite** [comment]
@pepelsbey поменяй, пожалуйста, в панели регистратора DNS-записи на новые:

```
dns1.p01.nsone.net
dns2.p01.nsone.net
dns3.p01.nsone.net
dns4.p01.nsone.net
```

В панели netlify я добавил алиас к new.doka.site

**Comment by pepelsbey** [comment]
> В панели netlify я добавил алиас к new.doka.site

А что это значит? :)

**Comment by pepelsbey** [comment]
> поменяй, пожалуйста, в панели регистратора DNS-записи на новые

Готово! Ждём до суток, чтобы везде разошлось

**Comment by furtivite** [comment]
> А что это значит? :

Пока ждём, и пока не снимем, будет доступна новая сборка по трём адресам: нетлифаевский внутренний (мы его публично не светим), new.y-doka.site и doka.guide. Как понадобится, лишние удалим.

**Comment by furtivite** [comment]
<img width="1037" alt="Снимок экрана 2021-06-09 в 13 37 53" src="https://user-images.githubusercontent.com/50330458/121340121-e5b9d200-c927-11eb-94ec-281ab17eef3a.png">

Работает. Всё хорошо. Let's Encrypt тоже подключен.
