### ISSUE TITLE
Уменьшение количества слоев Dockerfile

### ISSUE THREAD

**Issue by igsekor** [Y-Doka/platform#19]
Согласно рекомендациям команды Docker (https://docs.docker.com/develop/dev-best-practices/#how-to-keep-your-images-small), число слоев предлагается уменьшать, если это возможно. Рекомендация способствует уменьшению образа и кэша от образа. Поэтому есть предложение изменить Dockerfile на следующий вариант:

```bash
FROM node:lts-alpine

WORKDIR /platform
COPY . .

RUN npm install \
&& ln -sf ../content/css src/css \
&& ln -sf ../content/js src/js \
&& ln -sf ../content/html src/html

VOLUME /platform/content
EXPOSE 8080

ENTRYPOINT ["npm", "start"]
```

У меня образ собрался без проблем.

Получается четыре слоя вместо семи. Уменьшение слоев будет способствовать оптимизации хранения образов. Это особенно важно, если образ будет усложняться.

**Comment by nlopin** [comment]
@igsekor пришешь PR?

**Comment by igsekor** [comment]
@nlopin я сделал :)
