### ISSUE TITLE
Прокинуть переменные окружения в 11ty

### ISSUE THREAD

**Issue by furtivite** [Y-Doka/platform#58]
Необходимо создать [файл](https://www.11ty.dev/docs/data-js/#example-exposing-environment-variables), в котором прокинуть переменные окружения для использования внутри eleventy.

**Comment by furtivite** [comment]
Пока есть желание вынести туда
- урлы репозиториев
    - репозитория с платформой
    - репозитория с контентом

**Comment by nlopin** [comment]
Давай обновим описание тикета или закроем? Договорились использовать переменные окружения

**Comment by furtivite** [comment]
Делается через создание шорткодов
